name: actions
on:
  push:
    branches:
      - master
    pull_request:
jobs:
  golangci-lint:
    name: runner / golang0-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the go module directory
        uses: actions/checkout@v1
      - name: golangci-lint
        uses: reviewdog/action-glangci-lint@v1
        with:
           golangci_lint_flages: "--enable-all --timeout=10m --exclude-use-default=false --tests=false --disable=gochecknoinits,gochecknoglobals,exhaustive,nakedret,exhaustivestruct"
           workdir: pkg

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Set up go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.13

      - name: Check out code
        uses: actions/checkout@v1